version: 0.1.0.{build}


platform:
- x64
- Win32


configuration:
- Release


install:
 - choco install redis-64
 - redis-server --service-install
 - redis-server --service-start


build_script:
- set GENERATOR=Visual Studio 14 2015
- if %PLATFORM% == x64 set GENERATOR=%GENERATOR% Win64
- mkdir build
- cd build
- cmake .. -G "%GENERATOR%"
- cmake --build . --config %CONFIGURATION%
- cd ..


test_script:
- cd build
- ctest -C %CONFIGURATION% --output-on-failure
